[build]
  command = "echo \"Skipping Flask server start during Netlify build\""

[build.environment]
  PYTHON_VERSION = "3.13"

[[redirects]]
  from = "/login"
  to = "/"

[[headers]]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
